config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :cocktails, only: [:index, :show, :new, :create, :edit, :update] do
    resources :doses, only: %i[new create update]
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
  
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[show edit update]

  def index
    @cocktails = Cocktail.all
  end

  def show; end
  
  def new
    @cocktail = Cocktail.new
  end
  
  def create
    @cocktail = Cocktail.new(cocktail_params)
    
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end
  
  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
  
  
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, except: :destroy
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end
  
  private
  
  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
  
  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/edit.html.erb
<%= render './shared/form' %>

app/views/cocktails/index.html.erb
<div class="container">
  <h1 class="my-5 text-center text-white">Our Cocktails</h1>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-sm-4">
        <%= link_to cocktail_path(cocktail) do %>
          <div class="card mb-3">
            <% if cocktail.photo.attached? %>
              <%= cl_image_tag cocktail.photo.key, crop: :fill, class: "card-img-top", alt: "Card image cap" %>
            <% else %>
              <img class="card-img-top" src=<%= cocktail.picture_url %>>
            <% end %>
            <div class="card-body">
              <h5><%= cocktail.name %></h5>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<%= render './shared/form' %>

app/views/cocktails/show.html.erb
<div class="container">
  <%# <h1 class="my-5 text-center text-white">Receip</h1> %>
  <div class="">
    <div class="show-card">
      <% if @cocktail.photo.attached? %>
        <%= cl_image_tag @cocktail.photo.key, crop: :fill, class: "show-card-img", alt: "Card image cap" %>
      <% else %>
        <img class="show-card-img" src=<%= @cocktail.picture_url %>>
      <% end %>
      <div class="show-card-body">
        <div class="d-flex align-items-center mb-5">
          <h3 class="show-card-title"><%= @cocktail.name%></h3>
          <%= link_to edit_cocktail_path(@cocktail) do %>
            <i class="fas fa-edit"></i>
          <% end  %>
        </div>
          <div class="d-flex">
            <h5 class="mb-4">Add Ingredient</h5>
            <%= link_to new_cocktail_dose_path(@cocktail) do %>
              <i class="fas fa-plus"></i>
            <% end %>
          </div>
        <ul>
            <% @cocktail.doses.each do |dose| %>
              <% @cocktail.ingredients.each do |ingredient| %>
                <% if dose.ingredient_id == ingredient.id %>
                  <li>
                    <%= dose.description %>
                    <%= ingredient.name %>
                    <%= link_to dose_path(dose), method: :delete, data: {confirm: 'Are you sure?'} do %>
                      <i class="far fa-trash-alt"></i>
                    <% end %>
                  </li>
                <% end %>
              <% end %>
            <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container mt-5 text-white w-50">
  <%= simple_form_for([@cocktail, @dose]) do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.submit "Add", class: "btn btn-info" %>
    <%= link_to 'Cancel', cocktail_path(@cocktail), class: 'btn btn-dark' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless controller_name == 'pages' %>
      <%= render './shared/navbar' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner d-flex align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1583367455075-9b4f4c6735bb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80);">
  <div class="container text-center">
    <h1 class="mb-4">Let's have a drink!</h1>
    <p class="mb-4"><em>"Alcohol, the cause of and the solution to all of life's problems." -Homer J. Simpson</em></p>
    <%= link_to 'Cocktails', cocktails_path(), class: "btn btn-info py-2 px-4" %>
  </div>
</div>

app/views/shared/_form.html.erb
<div class="container mt-5 text-white w-50">
  <h1 class="text-center">Add a Cocktail</h1>
  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Add", class: "btn btn-info" %>
    <% if @cocktail.id %>
      <%= link_to 'Cancel', cocktail_path(@cocktail), class: 'btn btn-dark' %>
    <% else %>
      <%= link_to 'Cancel', cocktails_path, class: 'btn btn-dark' %>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="d-flex justify-center text-white">  
      <i class="fas fa-glass-martini-alt"></i>
      <h6 class="ml-2">Home</h6>
    </div>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Add a Cocktail", new_cocktail_path(@cocktail), class: "nav-link text-white" %>
      </li>
      <li class="nav-item active">
        <%= link_to "See all Cocktails", cocktails_path, class: "nav-link text-white" %>
      </li>
    </ul>
  </div>
</div>